name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential zip unzip openjdk-17-jdk python3 python3-pip

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install cython==0.29.33 pillow kivy buildozer

    - name: Build APK
      run: |
        yes | buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: screenmirror-apk
        path: bin/*.apk
